<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="1" time="5.230">
  <testcase classname="__main__.HzTest" name="test_hz" time="5.2302">
    <failure type="AssertionError">average rate (7.500Hz) exceeded maximum (2.500Hz)
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/opt/ros/groovy/share/rostest/nodes/hztest/hztest", line 115, in test_hz
    self._test_hz(hz, hzerror, topic, test_duration, wait_time)
  File "/opt/ros/groovy/share/rostest/nodes/hztest/hztest", line 188, in _test_hz
    (rate, self.max_rate))
  File "/usr/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
    </failure>
  </testcase>
  <system-out><![CDATA[Hz: 2.0
Hz Error: 0.5
Topic: camera/image_raw
Test Duration: 5.0
Waiting for messages
Starting rate measurement
Done waiting, validating results
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
